yc_token        = "your yandex cloud token"
yc_folder_id    = "your yandex cloud folder id"
db_name         = "your database name"
db_user         = "your database user"
db_password     = "your database password"
datadog_api_key = "your datadog api key"
datadog_app_key = "your datadog app key"
datadog_api_url = "your datadog api url"
